SELECT DISTINCT DEPTNO
    FROM EMP;

SELECT DISTINCT JOB, DEPTNO
    FROM EMP;

SELECT ENAME, SAL, SAL*12+COMM, COMM 
    FROM EMP;

String SQL = "SELECT ENAME, SAL, SAL*12+COMM AS "ANNSAL", COMM FROM EMP";

SELECT * FROM EMP ORDER BY SAL;

SELECT * FROM EMP ORDER BY SAL DESC;

SELECT * FROM EMP ORDER BY DEPTNO ASC, SAL DESC;

SELECT * FROM EMP WHERE DEPTNO = 30;

SELECT * FROM EMP WHERE DEPTNO = 30 AND JOB = 'SALESMAN';

SELECT * FROM EMP WHERE DEPTNO = 30 OR JOB = 'CLERK';

SELECT * FROM EMP WHERE SAL * 12 = 36000;

SELECT * FROM EMP WHERE SAL >= 3000;

SELECT * FROM EMP WHERE ENAME >= 'F';

SELECT * FROM EMP WHERE SAL != 3000;

SELECT * FROM EMP WHERE SAL ^=3000;

SELECT * FROM EMP WHERE NOT SAL = 3000;

SELECT * FROM EMP WHERE JOB = 'MANAGER'
                     OR JOB = 'SALESMAN'
                     OR JOB = 'CLERK';

SELECT * FROM EMP WHERE JOB IN ('MANAGER', 'SALESMAN', 'CLERK');

SELECT * FROM EMP WHERE JOB != 'MANAGER'
                    AND JOB <> 'SALESMAN'
                    AND JOB ^= 'CLERK';

SELECT * FROM EMP WHERE JOB NOT IN ('MANAGER', 'SALESMAN', 'CLERK');

SELECT * FROM emp WHERE sal >=2000 AND sal <=3000;

SELECT * FROM emp WHERE sal BETWEEN 2000 and 3000;

SELECT * FROM emp WHERE sal NOT BETWEEN 2000 and 3000;

SELECT * FROM emp WHERE ENAME LIKE 'S%';

SELECT * FROM EMP WHERE ENAME LIKE '_L%';

SELECT * FROM EMP WHERE ENAME LIKE '%AM%';

SELECT * FROM SOME_TABLE WHERE SOME_COLUMN LIKE 'A\_A%' ESCAPE '\';

SELECT ename, sal, sal*12+comm AS annsal, comm FROM emp;

SELECT * FROM emp WHERE comm = NULL;

SELECT * FROM emp WHERE comm IS NULL;

SELECT * FROM emp WHERE MGR IS NOT NULL;

SELECT * FROM emp WHERE sal > NULL AND comm IS NULL;

SELECT * FROM EMP WHERE SAL > NULL AND COMM IS NULL;

SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10
UNION SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 20;

SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10
UNION SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE DEPTNO = 20;

SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10
UNION SELECT EMPNO, ENAME, SAL
UNION 
SELECT EMPNO, ENAME, SAL, DEPTNO 
FROM EMP
WHERE DEPTNO = 10;

SELECT EMPNO, ENAME, SAL, DEPTNO 
FROM EMP
WHERE DEPTNO = 10;

/* 오라클로 배우는 데이터베이스 입문 저서 참고 */