SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
   WHERE DEPTNO = 10
  UNION ALL
  SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
   WHERE DEPTNO = 10;

SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
   WHERE DEPTNO = 10
  MINUS
  SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
   WHERE DEPTNO = 10;

SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
   WHERE DEPTNO = 10
  INTERSECT
  SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
   WHERE DEPTNO = 10;

/* 오라클로 배우는 데이터베이스 입문 저서 참고 */